void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(char c);
int _isalpha(char c);
int print_sign(char n);
int _abs(int num);
int print_last_digit(int num);
void jack_bauer(void);
void times_table(void);
int _putchar(char c);
